Berras Bio Lab1/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Berras_Bio_Lab1.Models;
using Berras_Bio_Lab1.Repository;

namespace Berras_Bio_Lab1.Controllers
{
    public class MovieController : Controller
    {
        private readonly BerrasBioDbContext _context;

        public MovieController(BerrasBioDbContext context)
        {
            _context = context;
        }

        // GET: Movie
        public async Task<IActionResult> Index()
        {
            return View(await _context.Movies.ToListAsync());
        }

        //// GET: Movie/Create
        //public IActionResult Create42Aa()
        //{
        //    return View();
        //}

        //// POST: Movie/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create42Aa([Bind("MovieModelId,Name,RunTime,Category,Description")] MovieModel movieModel)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(movieModel);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(movieModel);
        //}


        //// GET: Movie/Delete/5
        //public async Task<IActionResult> Delete42Aa(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var movieModel = await _context.Movies
        //        .FirstOrDefaultAsync(m => m.MovieModelId == id);
        //    if (movieModel == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(movieModel);
        //}

        //// POST: Movie/Delete/5
        //[HttpPost, ActionName("Delete42Aa")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed42Aa(int id)
        //{
        //    var movieModel = await _context.Movies.FindAsync(id);
        //    _context.Movies.Remove(movieModel);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool MovieModelExists(int id)
        {
            return _context.Movies.Any(e => e.MovieModelId == id);
        }
    }
}

Berras Bio Lab1/Controllers/ViewingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Berras_Bio_Lab1.Models;
using Berras_Bio_Lab1.Repository;

namespace Berras_Bio_Lab1.Controllers
{
    public class ViewingController : Controller
    {
        private readonly BerrasBioDbContext _context;

        public ViewingController(BerrasBioDbContext context)
        {
            _context = context;
        }

        // GET: Viewing
        public async Task<IActionResult> Index()
        {
            var viewingsList = await _context.Viewings
                .Where(v => v.StartTime.Date == DateTime.Today)
                .Include(v => v.Movie)
                .Include(v => v.Theater)
                .ToListAsync();

            return View(viewingsList.OrderBy(v => v.StartTime).ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string SortButton)
        {
            var viewings = await _context.Viewings
                .Where(v => v.StartTime.Date == DateTime.Today)
                .Include(v => v.Movie)
                .Include(v => v.Theater)
                .ToListAsync();

            if (SortButton == "Start time")
            {
                viewings = viewings.OrderBy(v => v.StartTime).ToList();
            }
            else if (SortButton == "Avaible seats")
            {
                viewings = viewings
                    .OrderByDescending(v => v.AvaibleSeats)
                    .ThenBy(v => v.StartTime)
                    .ToList();
            }

            return View(viewings);
        }


        // GET: Viewing/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewingModel = await _context.Viewings
                .Include(v => v.Movie)
                .Include(v => v.Theater)
                .FirstOrDefaultAsync(m => m.ViewingModelId == id);

            if (viewingModel == null)
            {
                return NotFound();
            }

            return View(viewingModel);
        }

        //// GET: Viewing/Create756Aa
        //// Only for development purposes
        //public IActionResult Create756Aa()
        //{
        //    ViewData["MovieModelId"] = new SelectList(_context.Movies, "MovieModelId", "Name");
        //    ViewData["TheaterModelId"] = new SelectList(_context.Theaters, "TheaterModelId", "Name");
        //    return View();
        //}

        //// POST: Viewing/Create756Aa
        //// Only for development purposes
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create756Aa([Bind("ViewingModelId,StartTime,AvaibleSeats,TotalSeats,TheaterModelId,MovieModelId")] ViewingModel viewingModel)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(viewingModel);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["MovieModelId"] = new SelectList(_context.Movies, "MovieModelId", "Category", viewingModel.MovieModelId);
        //    ViewData["TheaterModelId"] = new SelectList(_context.Theaters, "TheaterModelId", "Name", viewingModel.TheaterModelId);
        //    return View(viewingModel);
        //}

        //// GET: Viewing/Delete756Aa/5
        //// Only for development purposes
        //public async Task<IActionResult> Delete756Aa(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var viewingModel = await _context.Viewings
        //        .Include(v => v.Movie)
        //        .Include(v => v.Theater)
        //        .FirstOrDefaultAsync(m => m.ViewingModelId == id);
        //    if (viewingModel == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(viewingModel);
        //}

        //// POST: Viewing/Delete756Aa/5
        //// Only for development purposes
        //[HttpPost, ActionName("Delete756Aa")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed756Aa(int id)
        //{
        //    var viewingModel = await _context.Viewings.FindAsync(id);
        //    _context.Viewings.Remove(viewingModel);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

    }
}

Berras Bio Lab1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Berras Bio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="cinema-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark navbar-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Berras Bio</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Viewing" asp-action="index">Today's viewings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Movie" asp-action="index">Movie archive</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container gray-box">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Berras Bio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>